server:
  port: 8443
  ssl:
    enabled: true            
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/letsplay
      auto-index-creation: true

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 86400000

logging:
  level:
    org.springframework.security: INFO
