server:
port: 8443
ssl:
enabled: false # set to true when you add a keystore
key-store: classpath:keystore.p12
key-store-password: changeit
key-store-type: PKCS12


spring:
data:
mongodb:
uri: mongodb://localhost:27017/letsplay


security:
jwt:
# 256-bit base64 secret (example only — replace!)
secret: "u1YF3z0mH0Yw1cU1b9Xq8rM1g5yO5e3q2r8s4p6t8v0w2y4x6z8A0B2C4D6E8F0="
expiration-ms: 86400000


logging:
level:
org.springframework.security: INFO


# --- Postman smoke tests (quick) ---
# 1) Public GET products
# GET https://localhost:8443/products
# 2) Register
# POST https://localhost:8443/auth/register { name,email,password }
# 3) Login -> Token
# 4) Create product (with Bearer <token>)
# 5) Update/Delete product (owner or ADMIN)